export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const CLEAR_FILTER = "CLEAR_FILTER";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const GET_STATE = "GET_STATE";
export const SET_CURRENT_STATE = "SET_CURRENT_STATE";
export const GET_STATES = "GET_STATES";
export const ADD_STATE = "ADD_STATE";
export const EDIT_STATE = "EDIT_STATE";
export const DELETE_STATE = "DELETE_STATE";
export const STATE_ERROR = "STATE_ERROR";
export const CLEAR_STATE = "CLEAR_STATE";
export const FILTER_STATE = "FILTER_STATE";

export const GET_CITY = "GET_CITY";
export const SET_CURRENT_CITY = "SET_CURRENT_CITY";
export const GET_CITIES = "GET_CITIES";
export const ADD_CITY = "ADD_CITY";
export const EDIT_CITY = "EDIT_CITY";
export const DELETE_CITY = "DELETE_CITY";
export const CITY_ERROR = "CITY_ERROR";
export const CLEAR_CITY = "CLEAR_CITY";
export const FILTER_CITY = "FILTER_CITY";

export const GET_LOCATION = "GET_LOCATION";
export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const ADD_LOCATION = "ADD_LOCATION";
export const EDIT_LOCATION = "EDIT_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const LOCATION_ERROR = "LOCATION_ERROR";
export const CLEAR_LOCATION = "CLEAR_LOCATION";
export const FILTER_LOCATION = "FILTER_LOCATION";

export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const SET_CURRENT_EMPLOYEE = "SET_CURRENT_EMPLOYEE";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const EMPLOYEE_ERROR = "EMPLOYEE_ERROR";
export const CLEAR_EMPLOYEE = "CLEAR_EMPLOYEE";
export const FILTER_EMPLOYEE = "FILTER_EMPLOYEE";

export const GET_COMPANY = "GET_COMPANY";
export const SET_CURRENT_COMPANY = "SET_CURRENT_COMPANY";
export const GET_COMPANYS = "GET_COMPANYS";
export const ADD_COMPANY = "ADD_COMPANY";
export const EDIT_COMPANY = "EDIT_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const COMPANY_ERROR = "COMPANY_ERROR";
export const CLEAR_COMPANY = "CLEAR_COMPANY";
export const FILTER_COMPANY = "FILTER_COMPANY";

export const GET_SUPPLIER = "GET_SUPPLIER";
export const SET_CURRENT_SUPPLIER = "SET_CURRENT_SUPPLIER";
export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const ADD_SUPPLIER = "ADD_SUPPLIER";
export const EDIT_SUPPLIER = "EDIT_SUPPLIER";
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const SUPPLIER_ERROR = "SUPPLIER_ERROR";
export const CLEAR_SUPPLIER = "CLEAR_SUPPLIER";
export const FILTER_SUPPLIER = "FILTER_SUPPLIER";

export const GET_SUPPLIER_BRANCH = "GET_SUPPLIER_BRANCH";
export const SET_CURRENT_SUPPLIER_BRANCH = "SET_CURRENT_SUPPLIER_BRANCH";
export const GET_SUPPLIER_BRANCHS = "GET_SUPPLIER_BRANCHS";
export const ADD_SUPPLIER_BRANCH = "ADD_SUPPLIER_BRANCH";
export const EDIT_SUPPLIER_BRANCH = "EDIT_SUPPLIER_BRANCH";
export const DELETE_SUPPLIER_BRANCH = "DELETE_SUPPLIER_BRANCH";
export const SUPPLIER_BRANCH_ERROR = "SUPPLIER_BRANCH_ERROR";
export const CLEAR_SUPPLIER_BRANCH = "CLEAR_SUPPLIER_BRANCH";
export const FILTER_SUPPLIER_BRANCH = "FILTER_SUPPLIER_BRANCH";

export const GET_CATEGORY = "GET_CATEGORY";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";
export const GET_CATEGORYS = "GET_CATEGORYS";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
export const CLEAR_CATEGORY = "CLEAR_CATEGORY";
export const FILTER_CATEGORY = "FILTER_CATEGORY";

export const GET_CUSTOMER = "GET_CUSTOMER";
export const SET_CURRENT_CUSTOMER = "SET_CURRENT_CUSTOMER";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const EDIT_CUSTOMER = "EDIT_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const CUSTOMER_ERROR = "CUSTOMER_ERROR";
export const CLEAR_CUSTOMER = "CLEAR_CUSTOMER";
export const FILTER_CUSTOMER = "FILTER_CUSTOMER";

export const GET_CUSTOMER_BRANCH = "GET_CUSTOMER_BRANCH";
export const SET_CURRENT_CUSTOMER_BRANCH = "SET_CURRENT_CUSTOMER_BRANCH";
export const GET_CUSTOMER_BRANCHS = "GET_CUSTOMER_BRANCHS";
export const ADD_CUSTOMER_BRANCH = "ADD_CUSTOMER_BRANCH";
export const EDIT_CUSTOMER_BRANCH = "EDIT_CUSTOMER_BRANCH";
export const DELETE_CUSTOMER_BRANCH = "DELETE_CUSTOMER_BRANCH";
export const CUSTOMER_BRANCH_ERROR = "CUSTOMER_BRANCH_ERROR";
export const CLEAR_CUSTOMER_BRANCH = "CLEAR_CUSTOMER_BRANCH";
export const FILTER_CUSTOMER_BRANCH = "FILTER_CUSTOMER_BRANCH";

export const GET_PRODUCT_BRANCH = "GET_PRODUCT_BRANCH";
export const SET_CURRENT_PRODUCT_BRANCH = "SET_CURRENT_PRODUCT_BRANCH";
export const GET_PRODUCT_BRANCHS = "GET_PRODUCT_BRANCHS";
export const ADD_PRODUCT_BRANCH = "ADD_PRODUCT_BRANCH";
export const EDIT_PRODUCT_BRANCH = "EDIT_PRODUCT_BRANCH";
export const DELETE_PRODUCT_BRANCH = "DELETE_PRODUCT_BRANCH";
export const PRODUCT_BRANCH_ERROR = "PRODUCT_BRANCH_ERROR";
export const CLEAR_PRODUCT_BRANCH = "CLEAR_PRODUCT_BRANCH";
export const FILTER_PRODUCT_BRANCH = "FILTER_PRODUCT_BRANCH";

export const GET_PRODUCT = "GET_PRODUCT";
export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const FILTER_PRODUCT = "FILTER_PRODUCT";

export const GET_WARRANTY = "GET_WARRANTY";
export const SET_CURRENT_WARRANTY = "SET_CURRENT_WARRANTY";
export const GET_WARRANTYS = "GET_WARRANTYS";
export const ADD_WARRANTY = "ADD_WARRANTY";
export const EDIT_WARRANTY = "EDIT_WARRANTY";
export const DELETE_WARRANTY = "DELETE_WARRANTY";
export const WARRANTY_ERROR = "WARRANTY_ERROR";
export const CLEAR_WARRANTY = "CLEAR_WARRANTY";
export const FILTER_WARRANTY = "FILTER_WARRANTY";
